services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-backend
    working_dir: /var/www
    volumes:
      # Caches are essential for performance
      - ./app:/var/www/app:cached
      - ./routes:/var/www/routes:cached
      - ./resources:/var/www/resources:cached
      - ./public:/var/www/public:cached
      - ./config:/var/www/config:cached 
      - ./database:/var/www/database:cached 
    ports:
      - 8000:8000
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_CHARACTER_SET_SERVER: utf8mb4 
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - 33061:3306 # 3306:3306 causes conflicts
    volumes:
      - mysql_data:/var/lib/mysql

    # Health check pro MySQL
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  # For database administration
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8080:80
    depends_on:
      - mysql

volumes:
  mysql_data: